version: 2.17
jobs:
  build:
    working_directory: ~/opt/notifications
    docker:
      - image: circleci/node:latest
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh -p 22 circleci@SERVER_HOSTNAME "cd ${CODE_PATH}; git pull; npm ci; cd deployment; redeploy.sh";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: development
          context: dev-converse-api
