version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - deploy:
          name: pust to ec2
          command: ssh-o"StrictHostKeyChecking no"circleci@SERVER_HOSTNAME"cd ${CODE_PATH}; git pull; npm ci; cd deployment; redeploy.sh;"

workflows:
  version: 2
  deploy-dev:
    jobs:
      - build:
          filters:
            branches:
              only: development
          context: dev-converse-api
