version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4

defaults: &defaults
  docker:
    - image: circleci/python:3.7.1
jobs:
  deploy-production:
    <<: *defaults
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: 'coa-converseapi'
          tag: "${CIRCLE_SHA1}"
          extra-build-args: '--build-arg dbhost=${DBHOST}/
               --build-arg dbuser=${DBUSER}/
               --build-arg dbpassword=${DBPASSWORD}/
               --build-arg database=${DATABASE}/
               --build-arg wh_dbhost=${DBHOST}/
               --build-arg wh_dbuser=${DBUSER}/
               --build-arg wh_dbpassword=${DBPASSWORD}/
               --build-arg wh_database=${DATABASE}/
               --build-arg debugging=${DEBUGGING}/
               --build-arg firebase_service_account=${FIREBASE_SERVICE_ACCOUNT}/
               --build-arg firebase_db_url=${FIREBASE_DB_URL}/
               --build-arg logfile=${LOGFILE}/
               --build-arg application_link=${APPLICATION_LINK}/
               --build-arg notification_email_address=${NOTIFICATION_EMAIL_ADDRESS}?
               --build-arg sns_access_key=${SNS_ACCESS_KEY}/
               --build-arg sns_secret_key=${SNS_SECRET_KEY}/
               --build-are sns_region=${AWS_DEFAULT_REGION}/
               --build-arg port=8080'
      - aws-ecs/update-service:
          family: 'simplicityapi'
          cluster-name: 'simplicityapi_ecs_cluster'
          service-name: 'simplicityapi'
          container-image-name-updates: 'container=simplicityapi,tag=${CIRCLE_SHA1}'
          force-new-deployment: true
          verify-revision-is-deployed: true
          max-poll-attempts: 30
          poll-interval: 60
          fail-on-verification-timeout: false
  deploy-development:
    <<: *defaults
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: 'coa-converseapi'
          tag: "${CIRCLE_SHA1}"
          extra-build-args: '--build-arg dbhost=${DBHOST}/
                   --build-arg dbuser=${DBUSER}/
                   --build-arg dbpassword=${DBPASSWORD}/
                   --build-arg database=${DATABASE}/
                   --build-arg wh_dbhost=${DBHOST}/
                   --build-arg wh_dbuser=${DBUSER}/
                   --build-arg wh_dbpassword=${DBPASSWORD}/
                   --build-arg wh_database=${DATABASE}/
                   --build-arg debugging=${DEBUGGING}/
                   --build-arg firebase_service_account=${FIREBASE_SERVICE_ACCOUNT}/
                   --build-arg firebase_db_url=${FIREBASE_DB_URL}/
                   --build-arg logfile=${LOGFILE}/
                   --build-arg application_link=${APPLICATION_LINK}/
                   --build-arg notification_email_address=${NOTIFICATION_EMAIL_ADDRESS}?
                   --build-arg sns_access_key=${SNS_ACCESS_KEY}/
                   --build-arg sns_secret_key=${SNS_SECRET_KEY}/
                   --build-are sns_region=${AWS_DEFAULT_REGION}/
                   --build-arg port=4000'
      - aws-ecs/update-service:
          family: 'converse'
          cluster-name: 'converse_ecs_cluster'
          service-name: 'converse'
          container-image-name-updates: 'container=converse,tag=${CIRCLE_SHA1}'
          force-new-deployment: true
          verify-revision-is-deployed: true
          max-poll-attempts: 30
          poll-interval: 60
          fail-on-verification-timeout: false
workflows:
  build-deploy:
    jobs:
      - deploy-development:
          filters:
            branches:
              only: development
          context: converse-development

      - deploy-production:
          filters:
            branches:
              only:  master
          context: converse-production
          type: approval
